### PR TITLE
Feature/20230204 julian

### PR DESCRIPTION
**Pull request by Julian0701**
### DEVELOP
- [x] 002-Notification
- [x] 117-NavbarMobile
-  ~118-TradingHeaderMobile~
- ~119-TickerSelectorBoxMobile~
- ~120-TradingViewMobile~
- ~121-UserMobile~
- [x] 122-OrderSectionMobile
- [x] 123-TradeTabMobile
- [x] 124-PositionTabMobile
- [x] 125-OpenSubTabMobile
- [x] 126-HistorySubTabMobile

### CHECK LIST
- [Naming convention](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md) verification: checked
- Coding style verification: checked
- new Library: 0
- new Class / Component: 0
- new loop: 0
- new recursive: 0
- high risk: 0
- new sql: 0

### UML
- [Sequence Diagram (interaction between frontend and backend)](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00001.md)
- [Component Diagram](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDCP00001.md)

### CODE REVIEW

**Comment by Julian0701** [comment]
- take 6 hrs
- remain trade_tab_mobile toggle

**Comment by Julian0701** [comment]
- take 3 hrs

**Review by Luphia — APPROVED** [review]
- no bug found

**Review by arealclimber — APPROVED** [review]
no bug found

**Pull request merged**
